metadata.format.version = "1.1"

[versions]

jetbrains = "24.1.0"
ignite = "1.0.0"
mixin = "0.8.5"
mixinExtras = "0.3.5"
paperweight = "1.5.11"
shadow = "8.1.1"
spotless = "6.23.3"
paper = "1.20.4-R0.1-SNAPSHOT"

[libraries]
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains" }

ignite = { group = "space.vectrix.ignite", name = "ignite-api", version.ref = "ignite" }
mixin = { group = "org.spongepowered", name = "mixin", version.ref = "mixin" }
mixinExtras = { group = "io.github.llamalad7", name = "mixinextras-common", version.ref = "mixinExtras" }

build-paperweight = { module = "io.papermc.paperweight.userdev:io.papermc.paperweight.userdev.gradle.plugin", version.ref = "paperweight" }
build-shadow = { module = "com.github.johnrengelman:shadow", version.ref = "shadow" }
build-spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
